#ifndef ERROR_H
#define ERROR_H
enum errorname
{
	NO_ERROR=0,
	UNKNOWN_SYMBOL=1,
	STRING_TOO_LONG,
	WRONG_FORMAT_REAL_NUMBER,
	WRONG_FORMAT_INTEGER,
	UNFINISHED_STRING,
	UNFINISHED_PROGRAM,
	MISSING_SEMICN,
	DECLARATION_IS_NOT_START_WITH_TYPE,
	DECLARATION_HAVE_NO_EQL,
	DECLARATION_SHOULD_HAVE_A_ID,
	WRONG_ASSIGN_SYNTAX,
	WRONG_EXPRESSION,
	ARRAY_OVERFLOW,
	ARRAY_SUBVALUE_SHOULD_BE_INTEGER,
	USING_AN_ICON_WITHOUT_DECLARTION,
	ERROR_VARIABLEDELARTION,
	ERROR_DATA_TYPE,
	ERROR_FUNCTIONDELARATION,
	RE_DECLARATION,
	ERROR_SENTENCE,///²»¹»Ã÷È·
	ERROR_PROGRAM_STRUCTURE,
	ERROR_RETURN_TYPE,
	PARENT_DISMATCH,
	ERROR_FOR_SENTENCE,
	ERROR_IN_WRITE_SENTENCE,
	ERROR_IN_READ_SENTENCE,
	MISSING_WHILE,
	ERROR_CONDITION,
	TOO_MANY£ßCODE_AFTER_MAIN_FUNCTION,
	MISSING_SENTENCE
};
int error (int errortype);
#endif
